### ISSUE TITLE
Nové zadání a Jirka zaspal [ DEADLINE 6.1.2021 ] 

### ISSUE THREAD

**Issue by goramartin** [jiriklepl/NSWI130-Team-Project2#1]
- [ ] Projít si slajdy a Control Room řešení
- [ ] Minimálně 8 scénářů QA, bez ohledu na původní zadání
  - [x] rozhodnout, jakým formátem to budeme dělat
  - [x] alespoň 1 scénář na Testability nebo Usability
     - [x] Testability
     - [x] Usability
  - [x] alespoň 1 scénář na Interoperability nebo Modifiability 
     - [ ] Interoperability
     - [x] Modifiability
  - [x] scénáře (pozn. dopsat po vytvoření scenario name + QA type)
     - [x] 1. - Subsetability: Štěpán
     - [x] 2. - Availability: Štěpán
     - [x] 3. - Modifiability: Štěpán
     - [x] 4. - Extendiability: Jirka
       - [x] <del>Obrázek</del>: Štěpán
         - _Nahradil jsem ho dlouhým textem. Prosím mrkněte na to._
     - [x] 5. - Performance: Jirka
     - [x] 6. - Scalability: Martin
     - [x] 7. - Security: Martin
     - [x] 8. - <del>Interoperability</del> _neděláme_
     - [x] 9. - Testability: Martin
     - [x] 10. - Usability: Martin
  - [ ] Zkontrolovat scénář po někom jiném
     - [x] 1. - Subsetability Martin
     - [x] 2. - Availability Martin
     - [x] 3. - Modifiability Martin
     - [x] 4. - Extendiability 
     - [x] 5. - Performance Martin
     - [x] 6. - Scalability
     - [x] 7. - Security
     - [x] 8. - <del>Interoperability</del> _neděláme_
     - [x] 9. - Testability
     - [x] 10. - Usability
- [ ] Připravit prezentaci
- [ ] Rozhodnout, kdo bude prezentovat

**Comment by sstenchlak** [comment]
1. Subsetability - část systému už může být v produkci
